[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://terabyte-kvey.onrender.com"
    Access-Control-Allow-Credentials = "true"
